program: Lent/distill_sweep.py
method: grid
metric: 
  name: S Test
  goal: maximize
name: Contrastive Temperature Sweep
parameters: 
  contrast_temp: 
    distribution: uniform
    min: 0.01
    max: 1
  optimization.base_lr: 
    distribution: log_uniform_values
    min: 0.01
    max: 0.3
  nonbase_loss_frac:
    distribution: log_uniform_values
    min: 0.01
    max: 0.5
# early_terminate: 
#   type: hyperband
#   min_iter: 10
