model_type: RN18AP
dataset_type: DOMINOES
config_type: EXHAUSTIVE
distill_loss_type: JACOBIAN
aug_type: NONE

optimization:
  optimizer_type: SGD
  base_lr: 0.1
  weight_decay: 0.0
  momentum: 0.0
  final_lr: 0.001
  cosine_lr_schedule: true
  optimizer_kwargs: {}
dataset:
  data_folder: "data"
  output_size: null
  box_cue_size: 4
  box_cue_pattern: MANDELBROT
  use_augmentation: true
augmentation:
  alpha: 2.0
  beta: 1.5
  mix_prob: 0.6
  crop_prob: 0.7
  flip_prob: 0.8
dataloader:
  train_bs: 64
  test_bs: 64
  num_workers: 1
resnet_config:
  blocks_per_stage: 3
  _width_factor: 1
epochs: null
num_iters: 8000
min_iters: 300
eval_frequency: 100
num_eval_batches: 50
early_stop_patience: 20

log_to_wandb: true
is_sweep: false
save_model_as_artifact: false
save_model: false
teacher_save_path: null
wandb_project_name: null
wandb_run_name: null

base_distill_loss_type: KL
jacobian_loss_type: MSE
nonbase_loss_frac: 0.5
dist_temp: 30
jac_temp: 1
contrast_temp: 0.01
use_early_stop: false
s_layer: null
t_layer: null
student_save_path: null
