- dataset_num: 1
  loss_num: 0
  s_exp_num: 0
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 0
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 1
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 1
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 2
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 2
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 3
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 3
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 4
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 4
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 5
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 5
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 6
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 6
  student_num: 1
  t_exp_num: 3
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 0
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 0
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 1
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 1
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 2
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 2
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 3
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 3
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 4
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 4
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 5
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 5
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 6
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 6
  student_num: 1
  t_exp_num: 4
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 0
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 0
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 1
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 1
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 2
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 2
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 3
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 3
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 4
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 4
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 5
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 5
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 6
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 6
  student_num: 1
  t_exp_num: 5
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 0
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 0
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 1
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 1
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 2
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 2
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 3
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 3
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 4
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 4
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 5
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 5
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 0
  s_exp_num: 6
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
- dataset_num: 1
  loss_num: 1
  s_exp_num: 6
  student_num: 1
  t_exp_num: 6
  teacher_num: 1
