model_type: RN18AP
dataset_type: DOMINOES
aug_type: NONE
optimization:
  optimizer_type: SGD
  base_lr: 0.3
  weight_decay: 0.0
  momentum: 0.0
  final_lr: 0.001
  cosine_lr_schedule: true
  optimizer_kwargs: {}
dataset:
  data_folder: "data"
  output_size: null
dataloader:
  train_bs: 64
  test_bs: 32
  num_workers: 1
resnet_config:
  blocks_per_stage: 3
  _width_factor: 1
epochs: null
num_iters: 20000
eval_frequency: 100
num_eval_batches: 20
early_stop_patience: 3
is_sweep: false
log_to_wandb: true
save_model_as_artifact: true
teacher_save_path: null
wandb_project_name: null
wandb_run_name: null
