model_type: RN18AP
dataset_type: DOMINOES
config_type: EXHAUSTIVE
aug_type: NONE

optimization:
  optimizer_type: SGD
  base_lr: 0.1
  weight_decay: 0.0
  momentum: 0.0
  final_lr: 0.001
  cosine_lr_schedule: true
  clip_grad: 1
  optimizer_kwargs: {}
dataset:
  data_folder: "data"
  output_size: null
  box_cue_size: 4
  box_cue_pattern: MANDELBROT
  use_augmentation: false
augmentation:
  alpha: 2.0
  beta: 1.5
  mix_prob: 0.6
  crop_prob: 0.7
  flip_prob: 0.8
dataloader:
  train_bs: 64
  test_bs: 64
  num_workers: 1
resnet_config:
  blocks_per_stage: 3
  _width_factor: 1

epochs: null
num_iters: 20000
eval_frequency: 100
num_eval_batches: 50
early_stop_patience: 50
run_description: "Retrain teacher on A"

log_to_wandb: true
is_sweep: false
sweep_num: 5
save_model_as_artifact: true
save_model: true
teacher_save_path: null
wandb_project_name: ""
wandb_run_name: null

