method: bayes
metric: 
  name: S Loss
  goal: minimize
name: jac_frac_sweep
# program: run.py
# command: 
#   - ${env}
#   - ${interpreter}
#   - ${program}
#   - --file_path
#   - ${args_json_file}
parameters: 
  nonbase_loss_frac: 
    distribution: log_uniform
    min: -4
    max: -2.3
early_terminate: 
  type: hyperband
  min_iter: 5