model_type: RNW
student_model_type: RNW
dataset_type: DOMINOES
config_type: EXHAUSTIVE
distill_loss_type: BASE
aug_type: NONE

optimization:
  optimizer_type: SGD
  base_lr: 0.001
  weight_decay: 0.0
  momentum: 0.0
  final_lr: 0.0001
  cosine_lr_schedule: true
  clip_grad: 1
  optimizer_kwargs: {}
dataset:
  data_folder: "data"
  output_size: null
  box_cue_size: 4
  box_cue_pattern: RANDOM
  use_augmentation: false
augmentation:
  alpha: 2.0
  beta: 1.5
  mix_prob: 0.6
  crop_prob: 0.7
  flip_prob: 0.8
dataloader:
  train_bs: 128
  test_bs: 128
  num_workers: 1
wrn_config:
    blocks_per_stage: 8
    width_factor: 2
student_wrn_config:
    blocks_per_stage: 2
    width_factor: 2

epochs: null
num_iters: 20000
min_iters: 800
eval_frequency: 100
num_eval_batches: 50
early_stop_patience: 20

log_to_wandb: true
is_sweep: false
sweep_num: 5
save_model_as_artifact: false
save_model: false
log_teacher: true
teacher_save_path: null
wandb_project_name: ""
wandb_run_name: null
run_description: "WRN depth variation"

use_early_stop: false
base_distill_loss_type: KL
jacobian_loss_type: MSE
nonbase_loss_frac: null
dist_temp: 30
jac_temp: 1
contrast_temp: 0.1
s_layer: null
t_layer: null
student_save_path: null
